
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

config();
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js"
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
